server:
  port: 91
  context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://eureka2001.wyy.com:2001/eureka/,http://eureka2002.wyy.com:2002/eureka/,http://eureka2003.wyy.com:2003/eureka/
turbine:
  app-config: microservice-student   # \u6307\u5B9A\u8981\u76D1\u63A7\u7684\u5E94\u7528\u540D\u79F0
  clusterNameExpression: "'default'" #\u8868\u793A\u96C6\u7FA4\u7684\u540D\u5B57\u4E3Adefault
spring:
  application:
    name: turbine
